# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Dog.delete_all

Dog.create(breed: 'English Cocker Spaniel', color: 'golden', country_of_origin: 'England', friendly: true, image: 'http://www.canadogs.com/images/EngCockerpup11.jpg', history: 'Spaniel type dogs have been found in art and literature for almost 500 years.[4] Initially, spaniels in England were divided among land spaniels and water spaniels. The differentiation among the spaniels that led to the breeds that we see today did not begin until the mid-19th century. During this time, the land spaniels became a bit more specialised and divisions among the types were made based upon weight. According to the 1840 Encyclopedia of Rural Sports, Cockers were 12–20 lb (5.5–9 kg). At this time it was not uncommon for Cockers and Springers to come from the same litter. Even a puppy from a “Toy” sized lineage could grow to be a springer.')
Dog.create(breed: 'Pit Bull', color: 'white', country_of_origin: 'USA', friendly: false, image: 'http://animalfair.com/wp-content/uploads/2014/02/blue-pitbull-puppy1.jpg', history: 'Pit bulls were created by breeding bulldogs and terriers together to produce a dog that combined the gameness and agility of the terrier with the strength of the bulldog. In the United Kingdom, these dogs were used in blood sports such as bull-baiting, bear-baiting and cock fighting. These blood sports were officially eliminated in 1835 as Britain began to introduce animal welfare laws. Since dogfights were cheaper to organize and far easier to conceal from the law than bull or bear baits, blood sport proponents turned to pitting their dogs against each other instead. Dog fighting was used as both a blood sport (often involving gambling) and a way to continue to test the quality of their stock. For decades afterwards, dog fighting clandestinely took place in small areas of Britain and America. In the early 20th century pit bulls were used as catch dogs in America for semi-wild cattle and hogs, to hunt, and drive livestock, and as family companions. Some have been selectively bred for their fighting prowess.')
Dog.create(breed: 'Cockapoo', color: 'golden', country_of_origin: 'USA', friendly: true, image: 'http://www.breedersonline.co.uk/photos/3a/5514x10_1.jpg', history: 'A Cockapoo can be the result of mating either the American Cocker Spaniel or English Cocker Spaniel with a Poodle. They have been known in the United States since the 1950s.Purebred breed associations such as The Kennel Club, the American Kennel Club, the United Kennel Club, or the Canadian Kennel Club, do not recognize the Cockapoo. Due to their fashionable status, Cockapoos are one of the mixed breed dogs most susceptible to be bred by puppy farms or unscrupulous amateur breeders looking to maximize profit. Potential owners should very carefully research where they are purchasing their puppy from in order not to support this industry.')
Dog.create(breed: 'Bulldog', color: 'white', country_of_origin: 'England', friendly: true, image: 'http://buzzsharer.com/wp-content/uploads/2015/04/english-bulldog-cute-puppy.jpg', history: "The Bulldog is a breed with characteristically wide head and shoulders along with a pronounced mandibular prognathism. There are generally thick folds of skin on a Bulldog's brow; round, black, wide-set eyes; a short muzzle with characteristic folds called a knot above the nose; hanging skin under the neck; drooping lips and pointed teeth, and occasionally an underbite. The coat is short, flat, and sleek, with colours of red, fawn, white, brindle, and piebald.")

puts "Seeding has been done"
